//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.Componens
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prrrEntities : DbContext
    {
        public prrrEntities()
            : base("name=prrrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Docimentation> Docimentation { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Pass> Pass { get; set; }
        public virtual DbSet<Subdivision> Subdivision { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TheHost> TheHost { get; set; }
        public virtual DbSet<VisitPurpose> VisitPurpose { get; set; }
        public virtual DbSet<Visitor> Visitor { get; set; }
    }
}
